-- MySQL Script generated by MySQL Workbench
-- Thu Mar  6 10:32:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consulta` DEFAULT CHARACTER SET utf8 ;
USE `consulta` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `create` DATETIME NOT NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`personas` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `create` DATETIME NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `rut` INT NOT NULL,
  `idtipo_usuario` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `create` DATETIME NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipo_usuario_idx` (`idtipo_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_persona1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`idtipo_usuario`)
    REFERENCES `consulta`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`rut`)
    REFERENCES `consulta`.`personas` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`especialidad` (
  `idespecialidad` INT NOT NULL AUTO_INCREMENT,
  `tipo_especialidad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `create` DATETIME NOT NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`medicos` (
  `idmedicos` INT NOT NULL AUTO_INCREMENT,
  `idespecialidad` INT NOT NULL,
  `nombe` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`idmedicos`),
  INDEX `fk_medicos_especialidad1_idx` (`idespecialidad` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_especialidad1`
    FOREIGN KEY (`idespecialidad`)
    REFERENCES `consulta`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`citas` (
  `idcitas` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idmedicos` INT NOT NULL,
  `fecha_cita` DATE NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`idcitas`),
  INDEX `fk_consultas_usuarios1_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_citas_medicos1_idx` (`idmedicos` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `consulta`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_medicos1`
    FOREIGN KEY (`idmedicos`)
    REFERENCES `consulta`.`medicos` (`idmedicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta`.`consultas` (
  `idconsultas` INT NOT NULL AUTO_INCREMENT,
  `idcitas` INT NOT NULL,
  `motivo` VARCHAR(300) NOT NULL,
  `diagnostico` VARCHAR(100) NOT NULL,
  `tratamiento` VARCHAR(300) NOT NULL,
  `prescripcion` VARCHAR(300) NOT NULL,
  `create` DATETIME NOT NULL,
  PRIMARY KEY (`idconsultas`),
  INDEX `fk_consultas_citas1_idx` (`idcitas` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_citas1`
    FOREIGN KEY (`idcitas`)
    REFERENCES `consulta`.`citas` (`idcitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;