-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 19:55:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Edu_kit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Edu_kit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Edu_kit` DEFAULT CHARACTER SET utf8 ;
USE `Edu_kit` ;

-- -----------------------------------------------------
-- Table `Edu_kit`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`personas` (
  `rut` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(80) NOT NULL,
  `tipo_u` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`instituciones` (
  `id_institucion` INT NOT NULL AUTO_INCREMENT,
  `nombre_institucion` VARCHAR(45) NOT NULL,
  `contacto_principal` INT NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_institucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `personas_rut` INT NOT NULL,
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `instituciones_id_institucion` INT NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `activo` TINYINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_personas_idx` (`personas_rut` ASC) VISIBLE,
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tipo_usuario_idtipo_usuario` ASC) VISIBLE,
  INDEX `fk_usuarios_instituciones1_idx` (`instituciones_id_institucion` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_personas`
    FOREIGN KEY (`personas_rut`)
    REFERENCES `Edu_kit`.`personas` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `Edu_kit`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_instituciones1`
    FOREIGN KEY (`instituciones_id_institucion`)
    REFERENCES `Edu_kit`.`instituciones` (`id_institucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`materias` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `materia` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`profesores` (
  `id_profesores` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id_usuario` INT NOT NULL,
  `materias_id_usuario` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_profesores`),
  INDEX `fk_profesores_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_profesores_materias1_idx` (`materias_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_profesores_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `Edu_kit`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_materias1`
    FOREIGN KEY (`materias_id_usuario`)
    REFERENCES `Edu_kit`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`ACTIVIDADES_EFICACES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`ACTIVIDADES_EFICACES` (
  `id_act` INT NOT NULL AUTO_INCREMENT,
  `nombre_actividad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_act`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`REGISTRO_ACTIVIDAD_ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`REGISTRO_ACTIVIDAD_ALUMNO` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `fecha_realizacion` DATE NOT NULL,
  `ACTIVIDADES_EFICACES_id_alumno` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_registro`),
  INDEX `fk_REGISTRO_ACTIVIDAD_ALUMNO_ACTIVIDADES_EFICACES1_idx` (`ACTIVIDADES_EFICACES_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_REGISTRO_ACTIVIDAD_ALUMNO_ACTIVIDADES_EFICACES1`
    FOREIGN KEY (`ACTIVIDADES_EFICACES_id_alumno`)
    REFERENCES `Edu_kit`.`ACTIVIDADES_EFICACES` (`id_act`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`RENDIMIENTO_HISTORICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`RENDIMIENTO_HISTORICO` (
  `id_rendimiento` INT NOT NULL AUTO_INCREMENT,
  `escala_mejora` FLOAT NOT NULL,
  `promedio_general` FLOAT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_rendimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`alumnos` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id_usuario` INT NOT NULL,
  `REGISTRO_ACTIVIDAD_ALUMNO_id_registro` INT NOT NULL,
  `RENDIMIENTO_HISTORICO_id_alumno` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_alumno`),
  INDEX `fk_alumnos_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_alumnos_REGISTRO_ACTIVIDAD_ALUMNO1_idx` (`REGISTRO_ACTIVIDAD_ALUMNO_id_registro` ASC) VISIBLE,
  INDEX `fk_alumnos_RENDIMIENTO_HISTORICO1_idx` (`RENDIMIENTO_HISTORICO_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `Edu_kit`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_REGISTRO_ACTIVIDAD_ALUMNO1`
    FOREIGN KEY (`REGISTRO_ACTIVIDAD_ALUMNO_id_registro`)
    REFERENCES `Edu_kit`.`REGISTRO_ACTIVIDAD_ALUMNO` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_RENDIMIENTO_HISTORICO1`
    FOREIGN KEY (`RENDIMIENTO_HISTORICO_id_alumno`)
    REFERENCES `Edu_kit`.`RENDIMIENTO_HISTORICO` (`id_rendimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`tipo_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`tipo_material` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `tipo_material` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`MATERIALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`MATERIALES` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo_material_id_alumno` INT NOT NULL,
  `url_archivo_externo` VARCHAR(200) NOT NULL,
  `fecha_subida` DATETIME NOT NULL,
  `aprobado` TINYINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_alumno`),
  INDEX `fk_MATERIALES_tipo_material1_idx` (`tipo_material_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_MATERIALES_tipo_material1`
    FOREIGN KEY (`tipo_material_id_alumno`)
    REFERENCES `Edu_kit`.`tipo_material` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edu_kit`.`ASIGNACION_MATERIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edu_kit`.`ASIGNACION_MATERIAL` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `fecha_asignacion` DATETIME NOT NULL,
  `instituciones_id_institucion` INT NOT NULL,
  `MATERIALES_id_alumno` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_alumno`),
  INDEX `fk_ASIGNACION_MATERIAL_MATERIALES1_idx` (`MATERIALES_id_alumno` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_MATERIAL_instituciones1_idx` (`instituciones_id_institucion` ASC) VISIBLE,
  CONSTRAINT `fk_ASIGNACION_MATERIAL_MATERIALES1`
    FOREIGN KEY (`MATERIALES_id_alumno`)
    REFERENCES `Edu_kit`.`MATERIALES` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_MATERIAL_instituciones1`
    FOREIGN KEY (`instituciones_id_institucion`)
    REFERENCES `Edu_kit`.`instituciones` (`id_institucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

